### ISSUE TITLE
Crafting the Barrel Label crashes my game

### ISSUE THREAD

**Issue by mahilo3550** [maruohon/enderutilities#60] opened 2017-10-08 12:09 UTC
Minecraft 1.12, Ender Utilities 0.7.5. As soon as the crafting table is filled with the recipe (dark green ingot with 8 sticks around it), the game crashes.

**Comment by maruohon** [comment] 2017-10-08 14:48
Works fine for me. Please post the crash log so that I could have any idea what is going wrong, and also the Forge version you are using.

**Comment by maruohon** [comment] 2017-10-28 06:36
Any update on this? If not, then I'll close this because I can't reproduce it.

**Comment by maruohon** [comment] 2018-01-31 22:44
I'm closing this due to no response and not being able to reproduce on my end.

**Closed by maruohon** 2018-01-31 22:44 UTC
